[build-system]
requires = [
    "setuptools>=68",
    "wheel",
    "Cython>=3.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "niniel"
version = "0.9.0"
description="Small, simple, and fast math library concentrating on combinatorics on words."
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
